CREATE DATABASE IF NOT EXISTS user_form_db
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE user_form_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  info TEXT,
  email VARCHAR(255) NOT NULL,
  contact VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
